### ISSUE TITLE
Makefile aborts when multiple source files exist

### ISSUE THREAD

**Issue by FrankR85** [mmitch/cobol-travis#1]
If I add a file ```MYPGM.cbl``` to the ```src``` folder and run ```make``` there is an error:
```
for TEST in test/addition.cbl; do \
                cp src/helloworld.cbl src/todoliste.cbl SRCPRG && \
                cp $TEST UTESTS && \
                ../ZUTZCPC && \
                cobc -x --std=ibm -o unittest -I /vagrant/cobol/cobol-travis/cobol-unit-test/src/main/cobol/copy TESTPRG && \
                ./unittest; \
        done
cp: target 'SRCPRG' is not a directory
make[2]: *** [test] Error 1
```
This is because now the ```src``` folder as the destination of ```cp``` contains multiple files and so ```cp``` expects the ```TARGET```argument to be a directory - but it isn`t.

At the moment the ```make``` expects a single sourcefile with probably multiple testfiles.

It would be nice if we could extend it to support multiple source files with probably multiple testfiles each.
In reality, I want to have several submodules that can be tested individually.

How can we support multiple source files? We cleary need to make the connection what testfiles belong to what source file. I would opt for naming conventions.

**Comment by mmitch** [comment]
This _should_ work as of 82aee62e0323e9ff57e13828869515e3fafa1de3, just add multiple ``static ... from ...`` lines to your ``build.txt`` – but I did not try it yet.  _(edit: can't work because ``$<`` in a Makefile rule only expands to the first dependency)_

Further Todos:
* [x] add example project with multiple source files and multiple target binaries
* [x] test it!
* [ ] add documentation

**Comment by FrankR85** [comment]
I've just tested this. Works fine! :+1:

**Comment by mmitch** [comment]
Documentation is done via issue #8, so this can be closed.
