### ISSUE TITLE
 make[2]: *** No rule to make target `...', needed by `build/main/...'.  Stop.

### ISSUE THREAD

**Issue by FrankR85** [mmitch/cobol-travis#14]
I still need a little help... :-/

Locally I can build [my project](https://github.com/FrankR85/ToDoListe) successfully but with [Travis](https://api.travis-ci.org/v3/job/497202347/log.txt), there is a problem:
```
make[2]: *** No rule to make target `src/main/cobol/CGIUTIL.cbl', needed by `build/main/CGIUTIL.o'.  Stop.
```
What am I doing wrong here?

**Comment by mmitch** [comment]
Unix filesystems as well as proper Unix environments are case sensitive.  Travis expects it the right way™ while your local Windows environment accepts any kuddelmuddel of filenames…

Your `build.txt` refers to these source files `TODOHANDLER.cbl`, `CGIUTIL.cbl` and `TODOLISTE.cbl` while your source folder contains `TODOHANDLER.cbl`, `cgiutil.cbl` and `todoliste.cbl`.

To fix it, make sure to name the files as they are named in `build.txt` (or the other way around).
Look out: Inside the cobol source, `PROGRAM-ID.` needs the same case, too!

**Comment by mmitch** [comment]
commit aae3de7 throws an  error during `genmk.sh` which should be easier to understand than the `no rule to make target` error from `make`

**Comment by FrankR85** [comment]
This error message is clearly better! :-) 

Didn't you mention that the local build will now fail too, if there might be FileNotFound errors due to case insensitive OS? Just wanted to let you know that my local build is still fine. But this isn't important IMHO.

**Comment by mmitch** [comment]
The check won't work locally with your case insensitive OS. Consider this example:
* only the file `foo.txt` exists
* something checks for the existance of `FOO.TXT`
* the case insensitive OS happily tells you that `FOO.TXT` exists because there is a file named `foo.txt` _and that is considered to be the same name_

So you can't find those errors locally, but they will be easier to read in TravisCI :wink:
